### ISSUE TITLE
Error: HTTP failure: 401

### ISSUE THREAD

**Issue by ghost** [ropenscilabs/geoparser#11]
When trying to run the geoparser_q function it returns "Error: HTTP failure: 401".

**Comment by maelle** [comment]
Thanks for the bug report!

* I think you forgot to register for a key or to set it up as an environment variable cf https://github.com/ropensci/geoparser#installation (I recommend using `usethis::edit_r_environ()` to access .Renviron btw)

* I will add a better error message because that one isn't very helpful!

**Comment by ghost** [comment]
Thank you for your kind reply!

Cheers,

**Comment by maelle** [comment]
Glad it helped!

**Comment by maelle** [comment]
Am editing your comment to remove all the part added by your answering by email because it contains your name and email address that aren't available on your GitHub profile (so that you might now want to share),

**Comment by maelle** [comment]
@CurmudgeonPhD The new version on CRAN has a better behaviour (it errors if no key is either given as argument or saved in .Renviron). Thanks again for the bug report.
